import type { Metadata } from "next";
import Header from '../components/header/page'
import Sidebar from '../components/aside/page'
import styles from './styles.module.scss';
import Main from './tasks/main/page'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={styles.body}>
          <Header />
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
